// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC04OGQkQOnCsa6VhNo8-YFFeRR2OY8nS0',
    appId: '1:254406209636:web:0096fe4c6be2dc90852f71',
    messagingSenderId: '254406209636',
    projectId: 'offline-sync-app-e3982',
    authDomain: 'offline-sync-app-e3982.firebaseapp.com',
    storageBucket: 'offline-sync-app-e3982.firebasestorage.app',
    measurementId: 'G-4D36QDDP0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm3qtT2NIksWkEaG8et0PQrbEoo8cEiew',
    appId: '1:254406209636:android:c38f2efe3f113d73852f71',
    messagingSenderId: '254406209636',
    projectId: 'offline-sync-app-e3982',
    storageBucket: 'offline-sync-app-e3982.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnMq5mEHhGVKiI1ssGXIJ4sW97whjAQPY',
    appId: '1:254406209636:ios:fccfe5514ac43563852f71',
    messagingSenderId: '254406209636',
    projectId: 'offline-sync-app-e3982',
    storageBucket: 'offline-sync-app-e3982.firebasestorage.app',
    iosBundleId: 'com.example.ailoitte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnMq5mEHhGVKiI1ssGXIJ4sW97whjAQPY',
    appId: '1:254406209636:ios:fccfe5514ac43563852f71',
    messagingSenderId: '254406209636',
    projectId: 'offline-sync-app-e3982',
    storageBucket: 'offline-sync-app-e3982.firebasestorage.app',
    iosBundleId: 'com.example.ailoitte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC04OGQkQOnCsa6VhNo8-YFFeRR2OY8nS0',
    appId: '1:254406209636:web:77fe96e0dc8b95d7852f71',
    messagingSenderId: '254406209636',
    projectId: 'offline-sync-app-e3982',
    authDomain: 'offline-sync-app-e3982.firebaseapp.com',
    storageBucket: 'offline-sync-app-e3982.firebasestorage.app',
    measurementId: 'G-401BWQ5C6Y',
  );
}
